### PR TITLE
Added Sentry Monitoring

### PR DESCRIPTION
**Pull request by tsu-ki**
Resolves #(https://github.com/OWASP/Nest/issues/112)

@arkid15r can you please specify if I should create a DNS for Sentry, or one already exists for it. 
I'll test the proposed changes first and then update the PR accordingly

### CODE REVIEW

**Comment by yashpandey06** [comment]
@tsu-ki  run pre-commit

**Comment by yashpandey06** [comment]
@tsu-ki  any updates regarding the changes ...?

**Comment by tsu-ki** [comment]
@yashpandey06 I’ll push the changes tomorrow night as I have an interview scheduled for tomorrow afternoon and I’ve been busy preparing for that. My apologies for the delay

**Comment by yashpandey06** [comment]
> @yashpandey06 I’ll push the changes tomorrow night as I have an interview scheduled for tomorrow afternoon and I’ve been busy preparing for that. My apologies for the delay


Thanks for the updates ... actually we are sort of blocked on an issue for which we need sentry ...any way we can wait ...best of luck !!

**Comment by tsu-ki** [comment]
@yashpandey06  I apologise for that. If it’s an urgent task that needs to be resolved then please ping me on slack and I’ll coordinate the changes I’ve made so far and you can carry on the with it

**Comment by arkid15r** [comment]
This has been addressed in https://github.com/OWASP/Nest/pull/187

**Pull request closed without merging**
