### PR TITLE
Set up jest + ts + react-testing-library

### PR DESCRIPTION
**Pull request by Yashgupta9330**
setup jest + react testing library #79 
Screenshot 2024-11-27 014844

### CODE REVIEW

**Review by arkid15r — COMMENTED** [review]
It's a great improvement, now we have test frameworks set up for both BE/FE.
If no comments from other reviewers I'm merging this later today.

Let's focus on running FE tests in a docker container in a separate PR.

**Comment by arkid15r** [comment]
> setup jest + react testing library #79 Screenshot 2024-11-27 014844

btw, is

```
console.warn
    ⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath.

       6 |
       7 | test("renders Home page heading and the contribute link", () => {
    >  8 |   render(
         |         ^
       9 |     <BrowserRouter>
      10 |       <App />
      11 |     </BrowserRouter>

      at warnOnce (node_modules/react-router/lib/deprecations.ts:9:13)
      at logDeprecation (node_modules/react-router/lib/deprecations.ts:14:3)
      at Object.logV6DeprecationWarnings [as UNSAFE_logV6DeprecationWarnings] (node_modules/react-router/lib/deprecations.ts:37:5)
      at node_modules/react-router-dom/index.tsx:816:25
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23189:26)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24970:11)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24930:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24917:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24905:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27078:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:27023:14)
      at node_modules/react-dom/cjs/react-dom.development.js:26808:9
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:180:26)
      at render (node_modules/@testing-library/react/dist/pure.js:271:10)
      at Object.<anonymous> (__tests__/App.test.tsx:8:9)
```

something we should address before the merge?

**Comment by Yashgupta9330** [comment]
I will fix this

**Comment by tsu-ki** [comment]
@arkid15r @Yashgupta9330 Just a suggestion, shouldn't we setup ESLint and Husky or Jest first, and then make changes to the merged files; because doing it seperately may cause command/package version conflicts

**Comment by arkid15r** [comment]
> @arkid15r @Yashgupta9330 Just a suggestion, shouldn't we setup ESLint and Husky or Jest first, and then make changes to the merged files; because doing it separately may cause command/package version conflicts

Could you add more details about `command/package version conflicts`? My understanding is that we need just run linting/formatting once (either within this PR or separately right after this one is merged). Anyway, I appreciate the suggestion.

**Comment by tsu-ki** [comment]
> > @arkid15r @Yashgupta9330 Just a suggestion, shouldn't we setup ESLint and Husky or Jest first, and then make changes to the merged files; because doing it separately may cause command/package version conflicts
> 
> Could you add more details about `command/package version conflicts`? My understanding is that we need just run linting/formatting once (either within this PR or separately right after this one is merged). Anyway, I appreciate the suggestion.

@arkid15r In my updated ESLint setup, i'm running `npm run prepare` for setting up husky and `.husky/pre-commit`, so I was wondering if something could be done here. 
In the package.json file, I've added several new scripts for the Lint-Husky setup and was just curious if those could cause a conflict with this Jest setup

**Pull request merged**
