### PR TITLE
Fix jest/no-mock-import error 

### LINKED ISSUE #163: Fix `jest/no-mock-import` error
**Describe the bug**
`make check` errors with 

```
/home/owasp/__tests__/src/pages/Projects.test.tsx
  5:1  error  Mocks should not be manually imported from a __mocks__ directory. Instead use `jest.mock` and import from the original module path  jest/no-mocks-import

✖ 1 problem (1 error, 0 warnings)

``` 

**To Reproduce**
run `make check`

**Expected behavior**
No error even after removing [suppressing configuration rule](https://github.com/OWASP/Nest/blob/5c97d180776f97148cbc688f905d0e11444b4218/frontend/eslint.config.js#L59)

**Additional context**
The rule in [eslint.config.js](https://github.com/OWASP/Nest/blob/5c97d180776f97148cbc688f905d0e11444b4218/frontend/eslint.config.js#L59) needs to be removed. The mock data needs to be used in a way that won't produce the error.

### PR DESCRIPTION
**Pull request by Rajgupta36**
Resolves #163 

## Tasks:

- [x] **Change the Directory Structure:** placed `mockdata` and `test` in the same directory.
- [x] Updated Jest config to resolve the import and mock issues.
- [x] Remove Lint Rule Related to Jest.
- [x] Added necessary type definitions for Mocha to improve type-checking in tests.

### Testing:
image

### Linting Checks:
image

### CODE REVIEW

**Comment by Rajgupta36** [comment]
@arkid15r sir, pls review this pr

**Review by arkid15r — CHANGES_REQUESTED** [review]
It seems the mocks directory needs to be removed from the `frontend/Dockerfile.test`
Use `make test` to test your changes locally

**Comment by Rajgupta36** [comment]
> It seems the mocks directory needs to be removed from the `frontend/Dockerfile.test` Use `make test` to test your changes locally

okk

**Comment by Rajgupta36** [comment]
@arkid15r , I updated the test Dockerfile and added layering to optimize the build and improve cachingimage

**Review by arkid15r — APPROVED** [review]
LGTM 👍

**Pull request merged**
