### PR TITLE
Added Introductory Unit tests and Restructured the test folder

### PR DESCRIPTION
**Pull request by yashpandey06**
Ref : #93 

# Changes Included in the Pull Request

## Overview
This document provides a high-level summary of the changes made in this pull request. The changes focus on adding unit tests for the `Projects` component, refactoring mock data for reusability, and improving the overall test structure.

---

### 1. **Unit Tests for `Projects` Component**
- Added a test file `Projects.test.tsx` to verify the functionality and rendering of the `Projects` component.
- The tests ensure that:
  - Project data is fetched and rendered correctly.
  - The project name, summary, and "Contribute" button are displayed as expected.

### 2. **Refactored Mock Data**
- Moved mock project data to a dedicated file in the `__mocks__` directory:

- The mock data simulates API responses and is reusable across multiple test files.

### 3. **Environment Variable Setup**
- Added `process.env.VITE_NEST_API_URL` in the test environment to simulate the API URL.

### 4. **Improved Test Structure**
- Cleaned up test files by separating mock data from test logic.
- Used `beforeEach` and `afterEach` to set up and tear down mocks for better test isolation.

---

### 1. **Test File**
- **`Projects.test.tsx`**:
- Contains unit tests for the `Projects` component.
- Verifies that the component renders project data correctly and handles asynchronous operations.

### 2. **Mock Data File**
- **`__mocks__/mockProjectData.ts`**:
- Contains reusable mock project data for testing.
- Simulates API responses for the `Projects` component.

### 3. **Component File**
- No changes were made to the `Projects` component itself.

---

Screenshot 2024-12-03 at 11 01 53 PM

### CODE REVIEW

**Comment by yashpandey06** [comment]
@arkid15r  please help review this PR

**Review by arkid15r — COMMENTED** [review]
Thanks for adding this!

I know it worked when you created the PR -- after that I've merged a bunch of changes.
Can we address the issue we discussed in Slack in this PR: the one w/ the new Projects page tests (`Property 'env' does not exist on type 'ImportMeta'`)

Screenshot 2024-12-03 at 3 12 53 PM

I'd really appreciate your help with resolving this (I can't add the new frontend tests step for CI/CD as it's currently broken).

**Comment by yashpandey06** [comment]
@arkid15r  please help review these changes.

**Comment by arkid15r** [comment]
> @arkid15r please help review these changes.

I commented it on Slack -- I'm seeing some errors when run it locally

**Review by arkid15r — APPROVED** [review]
LGTM 👍

**Pull request merged**
